site_name: Z$ Learning Hub
site_description: Patterns, recipes, and notes I reuse across finance, ops, and creative work.
site_url: https://zacharymplace.github.io/learning-hub/
repo_url: https://github.com/zacharymplace/learning-hub
edit_uri: edit/main/docs/
repo_name: learning-hub
copyright: "© {{ date | strftime('%Y') }} Z$"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.action.view
    - content.action.edit
    - search.suggest
    - search.highlight
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true 

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - How-To:
      - Power Query Hand-off Patterns: how-to/power-query-handoff.md
      - Mermaid Gallery: how-to/mermaid-gallery.md
      - Pandas I/O Cheats: how-to/pandas-io.md
      - Forecast rollups (monthly → quarterly): how-to/forecast-rollups.md
      - Lease CSV cleanup (ASC 842 prep): how-to/lease-csv-cleanup.md
  - Snippets:
      - SQL: snippets/sql.md
      - Python: snippets/python.md
  - Reference:
      - Conventions: reference/conventions.md
  - Examples: examples.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zacharymplace
      name: GitHub • zacharymplace
    # add more later (X, YouTube, etc.)
