site_name: Z$ Learning Hub
site_description: Patterns, recipes, and notes I reuse across finance, ops, and creative work.
site_url: https://zacharymplace.github.io/learning-hub/
repo_url: https://github.com/zacharymplace/learning-hub
repo_name: learning-hub
copyright: "© {{ date | strftime('%Y') }} Z$"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.code.copy
    - content.action.view
    - search.suggest
    - search.highlight
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - How-To:
      - Pandas I/O Cheats: how-to/pandas-io.md
      - Mermaid → PNG: how-to/mermaid-export.md
  - Snippets:
      - SQL: snippets/sql.md
      - Python: snippets/python.md
  - Reference:
      - Conventions: reference/conventions.md
