name: Generate PQ Handoff Examples
on:
  workflow_dispatch: {}
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXAMPLES_DIR: docs/examples
    steps:
      - name: Checkout (main)
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyarrow

      - name: Generate sample files
        run: |
          python scripts/python/generate_pq_handoff_examples.py --outdir "${EXAMPLES_DIR}"
          ls -lah "${EXAMPLES_DIR}" || true

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [ -d "${EXAMPLES_DIR}" ]; then
            git add "${EXAMPLES_DIR}/"
          else
            echo "Expected directory ${EXAMPLES_DIR} not found"; exit 1
          fi

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(examples): refresh PQ handoff sample files"
            git push origin main
          fi
