name: lint
on:
  push:
    branches: [ main ]
    paths:
      - "**/*.py"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**/*.py"
      - ".github/workflows/lint.yml"

jobs:
  # whatever you already run (ruff/black/mypy, etc.)
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # your existing lint steps here
