name: Render Mermaid diagrams
on:
  push:
    paths:
      - "docs/diagrams/**.mmd"
      - ".github/puppeteer.json"
  workflow_dispatch: {}

permissions:
  contents: write   # allow committing rendered SVGs

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: '18' }

      - name: Install Mermaid CLI
        run: npm i -g @mermaid-js/mermaid-cli

      - name: Render to SVG
        shell: bash
        run: |
          shopt -s nullglob
          mkdir -p docs/assets/diagrams
          for f in docs/diagrams/*.mmd; do
            base=$(basename "$f" .mmd)
            mmdc -p .github/puppeteer.json \
                 -i "$f" \
                 -o "docs/assets/diagrams/$base.svg" \
                 -b transparent -t neutral
          done

      - name: Commit rendered diagrams
        shell: bash
        run: |
          if [[ -n "$(git status --porcelain docs/assets/diagrams)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/assets/diagrams
            git commit -m "chore(diagrams): render mermaid SVGs"
            git push
          fi
