name: Path Guard

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: {}

jobs:
  path-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Block hardcoded local paths
        shell: bash
        run: |
          set -euo pipefail
          # Search tracked files for forbidden local paths.
          # Exclude this workflow file so the literals below don't trigger.
          if git grep -nF \
            -e 'C:/Users/Zacha/code/' \
            -e 'C:\\Users\\Zacha\\code\\' \
            -e 'Users/Zacha/code/' \
            -- . ':(exclude).github/workflows/path-guard.yml' ; then
            echo "::error::Found hardcoded local paths. Replace with relative repo paths."
            exit 1

::contentReference[oaicite:0]{index=0}
